### PR TITLE
fix: limit max weights sum

### LINKED ISSUE #350: Limit the weights sum
To prevent u64 overflow (and signed long overflow on Java side) we want to limit the sum of weights to 2^63.

### PR DESCRIPTION
**Pull request by anthony-swirldslabs**
**Description**:
Limit the maximum sum of weights to 2^63 which doesn't overflow Java signed `long`, and certainly doesn't overflow Rust `u64`.

**Related issue(s)**:

Fixes #350 

**Notes for reviewer**:
A new test is added.

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

File: cryptography/hedera-cryptography-hinTS/src/main/java/com/hedera/cryptography/hints/HintsLibraryBridge.java [hunk 1]
```diff
@@ -15,6 +15,9 @@ public class HintsLibraryBridge {
     /** The max number of signers that we can support w/o running into OutOfMemory as the memory usage is quadratic. */
     private static final short MAX_SIGNERS_NUM = (short) 1023;
 
+    /** The max theoretical sum of weights all nodes together can have, which is 2^63 because we use signed long. */
+    private static final long MAX_SUM_OF_WEIGHTS = Long.MAX_VALUE;
```
Comment (rsinha) [inline cryptography/hedera-cryptography-hinTS/src/main/java/com/hedera/cryptography/hints/HintsLibraryBridge.java:19]: I am not very familiar, but Long.MAX_VALUE equals 2^63 - 1. Is that correct? Whereas we allow the sum to be 2^63?

File: cryptography/hedera-cryptography-hinTS/src/main/java/com/hedera/cryptography/hints/HintsLibraryBridge.java [hunk 2]
```diff
@@ -351,4 +358,17 @@ private static int inferNFromCRSLength(final byte[] crs) {
...
     }
+
+    /** Check if the sum of weights doesn't exceed MAX_SUM_OF_WEIGHTS. */
+    public static boolean validateWeightsSum(final long weights[]) {
+        try {
+            long sum = 0;
+            for (int i = 0; i < weights.length; i++) {
+                sum = Math.addExact(sum, weights[i]);
+            }
+            return sum >= 0L && sum <= MAX_SUM_OF_WEIGHTS;
```
Comment (rsinha) [inline cryptography/hedera-cryptography-hinTS/src/main/java/com/hedera/cryptography/hints/HintsLibraryBridge.java:370]: Do we want to check for overflow in each iteration of the loop?

File: cryptography/hedera-cryptography-hinTS/src/main/java/com/hedera/cryptography/hints/HintsLibraryBridge.java (hunk 1 above)
Comment (anthony-swirldslabs) [reply cryptography/hedera-cryptography-hinTS/src/main/java/com/hedera/cryptography/hints/HintsLibraryBridge.java:19]: Correct, it's 2^63-1. This is the maximum positive long that the Consensus Node code could store in a `long`. I've updated the javadoc accordingly.

File: cryptography/hedera-cryptography-hinTS/src/main/java/com/hedera/cryptography/hints/HintsLibraryBridge.java (hunk 2 above)
Comment (anthony-swirldslabs) [reply cryptography/hedera-cryptography-hinTS/src/main/java/com/hedera/cryptography/hints/HintsLibraryBridge.java:370]: We do. The addExact() would throw if the sum overflows. I've added a clarifying comment in code.

**Review by rsinha — APPROVED** [review]

**Review by andrewb1269 — APPROVED** [review]
