### PR TITLE
fix: checking for point at infinity in hints

### LINKED ISSUE #571: Extended Public Key Zero Element Acceptance
The verify_hint() function in HIP-1200 validates extended public keys (hints) submitted by parties during the setup phase. However, it does not check for zero/identity elements in the cryptographic components. This allows a malicious party to submit a hint where all elliptic curve points are set to the identity element (zero point).

### PR DESCRIPTION
**Pull request by rsinha**
**Description**:
This PR checks that the submitted hint does not contain "bogus" zero group elements. Fixes https://github.com/hashgraph/hedera-cryptography/issues/571.

### CODE REVIEW

**Review by anthony-swirldslabs — DISMISSED** [review]

**Review by lpetrovic05 — DISMISSED** [review]

File: cryptography/hedera-cryptography-hints/src/test/java/com/hedera/cryptography/hints/HintsLibraryBridgeTest.java [hunk 1]
```diff
@@ -30,6 +30,12 @@ void setup() {
         INSTANCE.resetCache();
     }
 
+    byte[] initAndUpdateCRS(short n) {
```
Comment (rsinha) [inline cryptography/hedera-cryptography-hints/src/test/java/com/hedera/cryptography/hints/HintsLibraryBridgeTest.java:33]: Do you mean to use `n` below instead of 4?

Comment (anthony-swirldslabs) [reply cryptography/hedera-cryptography-hints/src/test/java/com/hedera/cryptography/hints/HintsLibraryBridgeTest.java:33]: Just fixed that.

**Review by anthony-swirldslabs — APPROVED** [review]
