### PR TITLE
fix: Respect prefixes for different OS

### LINKED ISSUE #81: Rust: Windows DLL loading is not using correct file name
### Description

The DLL compiled for Windows does not have the `lib` prefix, which means for the library `bn254` the file is called `bn254.dll` and **not** `libbn254.dll`.

We could probably rename the file as part of the build if we want that solution, but maybe it is more consistent with common standards to not prepend the "lib" prefix for Windows in the loading code.

### Steps to reproduce

I created a setup that runs the `hedera-cryptography-altbn128` tests on Windows on CI on top of #70.
It's failing to load the file, although it was created.
- https://github.com/hashgraph/hedera-cryptography/actions/runs/11363866764/job/31608808094
- https://scans.gradle.com/s/q23d7xbiz4cc2/tests/overview

### Additional context

_No response_

### Hedera network

_No response_

### Version

develop

### Operating system

Windows

### PR DESCRIPTION
**Pull request by timo0**
Fix #81

### CODE REVIEW

File: common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java [hunk 1]
```diff
@@ -155,12 +168,20 @@ public String locationInJar() {
...
         Objects.requireNonNull(libraryName, "name must not be null");
+        Objects.requireNonNull(libPrefixes, "libPrefixes must not be null");
         Objects.requireNonNull(libExtensions, "libExtensions must not be null");
         final OperatingSystem os = OperatingSystem.current();
         final Architecture arch = Architecture.current();
 
+        String libPrefix = libPrefixes.get(os);
+        if (libPrefix == null) {
+            libPrefix = "";
+        }
```
Comment (mxtartaglia-sl) [inline common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java]: MAybe a.getOrDefault() to avoid some lines of code.
```suggestion
        final String libPrefix = libPrefixes.getOrDefault(os,"");
```

File: common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java [hunk 2]
```diff
@@ -50,7 +50,7 @@ private static Stream<Object[]> combinedParameters() {
     void testWithNameAndCustomExtensions(OperatingSystem operatingSystem, Architecture architecture) {
         final Map<OperatingSystem, String> extensions =
                 Map.of(OperatingSystem.WINDOWS, "win", OperatingSystem.LINUX, "lx", OperatingSystem.DARWIN, "dar");
-        NativeLibrary library = NativeLibrary.withName("libcustom", extensions);
+        NativeLibrary library = NativeLibrary.withName("custom", extensions, extensions);
```
Comment (mxtartaglia-sl) [inline common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java]: For this case I would not reuse the same map. Just to make sure that whatever was sent as extension was  used as extension, and what was sent as prefix was used as prefix

File: common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java [hunk 3]
```diff
@@ -128,14 +129,14 @@ public void testInstallExistentLib() {
 
     @Test
```
Comment (mxtartaglia-sl) [inline common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java:153]: Can you add a test case scenario where it is informed only to a specific `os`, an check that for that os the prefix comes informed and for the rest is blank?

File: common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java [hunk 4]
```diff
@@ -83,11 +83,18 @@ public class NativeLibrary {
     private static final Map<OperatingSystem, String> DEFAULT_LIB_EXTENSIONS =
             Map.of(OperatingSystem.WINDOWS, "dll", OperatingSystem.LINUX, "so", OperatingSystem.DARWIN, "dylib");
 
+    /**
+     * Default prefix for binary libraries per OS
+     */
+    private static final Map<OperatingSystem, String> DEFAULT_LIB_PREFIXES =
+            Map.of(OperatingSystem.WINDOWS, "", OperatingSystem.LINUX, "lib", OperatingSystem.DARWIN, "lib");
```
Comment (mxtartaglia-sl) [inline common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java:90]: We would only save some bits that would always be in memory,  but if we have an if statement that takes care of this case, we might as well not set the empty value for windows. ..

File: common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java [hunk 5]
```diff
@@ -102,7 +103,7 @@ void testWithNameAndEmptyExtensions(OperatingSystem operatingSystem, Architectur
     void testWithNameAndBlankExtensions(OperatingSystem operatingSystem, Architecture architecture) {
         final Map<OperatingSystem, String> extensions =
                 Map.of(OperatingSystem.WINDOWS, "", OperatingSystem.LINUX, "", OperatingSystem.DARWIN, "");
-        NativeLibrary library = NativeLibrary.withName("libcustom", extensions);
+        NativeLibrary library = NativeLibrary.withName("custom", extensions, extensions);
```
Comment (mxtartaglia-sl) [inline common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java]: The name `extensions` is not accurate anymore if we are reusing the map

File: common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java (hunk 1 above)
Comment (timo0) [reply common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java]: done :)

File: common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java (hunk 2 above)
Comment (timo0) [reply common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java]: done

File: common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java (hunk 3 above)
Comment (timo0) [reply common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java:153]: Added `testWithOnlyOneOsPrefix`

File: common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java (hunk 4 above)
Comment (timo0) [reply common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java:90]: Sorry disagree with that this is more explicit and would like to keep that

File: common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java (hunk 5 above)
Comment (timo0) [reply common/hedera-common-nativesupport/src/test/java/com/hedera/common/nativesupport/NativeLibraryTest.java]: done

File: common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java (hunk 4 above)
Comment (mxtartaglia-sl) [reply common/hedera-common-nativesupport/src/main/java/com/hedera/common/nativesupport/NativeLibrary.java:90]: Makes sense

**Review by mxtartaglia-sl — APPROVED** [review]
